In [1]:
#1 (a) 
import numpy as np
arr = np.array([1,2,3,6,4,5])
print('Initial array', str(arr))
rev = arr[::-1]
print('Reversed array', str(rev))

Initial array [1 2 3 6 4 5]
Reversed array [5 4 6 3 2 1]


In [2]:
#1 (b) 
import numpy as numpy
arr1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
print(str(arr1))
arr1.flatten()

[[1 2 3]
 [2 4 5]
 [1 2 3]]


array([1, 2, 3, 2, 4, 5, 1, 2, 3])

In [ ]:
#1 (b) 
import numpy as ad

array1= ad.array([[1,2,3],[2,4,5],[1,2,3]])

rem = array1.ravel()

print("final array", str(rem))

final array [1 2 3 2 4 5 1 2 3]


In [3]:
#1 (c)
import numpy as np
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[1,2],[3,4]])
np.array_equal(arr1 , arr2)

True

In [4]:
#1 (d) 1
import numpy as np
arr1=np.array([1,2,3,4,5,1,2,1,1,1])
arr2=np.array([1,1,1,2,3,4,2,4,3,3])

print("most freq in 1:" ,np.bincount(arr1).argmax())
print("most freq in 2:" ,np.bincount(arr2).argmax())

print('with instance of arr 2')
k = np.bincount(arr2)
maximum=max(k)

for i in range(len(k)):
  if k[i] == maximum:
    print(i)

most freq in 1: 1
most freq in 2: 1
with instance of arr 2
1
3


In [ ]:
#1 (d) 2
import numpy as ad

y = ad.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
count=ad.bincount(y)
m=ad.argmax(count)
print("Most frequent value is",m)
result=ad.where(y==m)
print("Indices where the most frequent value occurs is",result)


Most frequent value is 1
Indices where the most frequent value occurs is (array([0, 1, 2]),)


In [8]:
#1 (e) 
import numpy as np
x = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print("Original array:")
print(x)
print("Sum of all elements:")
print(np.sum(x))
print("Sum of each column:")
print(np.sum(x, axis=0))
print("Sum of each row:")
print(np.sum(x, axis=1))

Original array:
[[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]
Sum of all elements:
45
Sum of each column:
[[20  9 16]]
Sum of each row:
[[14]
 [16]
 [15]]


In [9]:
#1 (f) 1
import numpy as np
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
diag = np.diagonal(n_array)  
print("Sum of Diagonal elements is:")
print(sum(diag))

Sum of Diagonal elements is:
176


In [10]:
#1 (f) 2,3
import numpy as np
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
w, v = np.linalg.eig(n_array)
print("Eigen values of the given square array:",w)
print("Eigenvectors of the given square array:",v)

Eigen values of the given square array: [98.16835147 28.097044   49.73460452]
Eigenvectors of the given square array: [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]


In [11]:
#1 (f) 4
import numpy as np
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
y = np.linalg.inv(n_array)
print("Inverse of the given square array:",y)


Inverse of the given square array: [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]


In [12]:
#1 (f) 5
import numpy as np
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
y = np.linalg.det(n_array)
print("Determinant of the given square array:",y)


Determinant of the given square array: 137180.0000000001


In [13]:
#1 (g) 1
import numpy as np
p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])
print("Multiplication:",np.dot(p,q))
print("Covariance matrix:",np.cov(np.dot(p,q)))

Multiplication: [[16 19]
 [26 31]]
Covariance matrix: [[ 4.5  7.5]
 [ 7.5 12.5]]


In [14]:
#1 (g) 2
import numpy as np
p = np.array([[1, 2], [2, 3], [4, 5]])
q = np.array([[4, 5, 1], [6, 7, 2]])
print("Multiplication:",np.dot(p,q))
print("Covariance matrix:",np.cov(np.dot(p,q)))

Multiplication: [[16 19  5]
 [26 31  8]
 [46 55 14]]
Covariance matrix: [[ 54.33333333  89.16666667 158.83333333]
 [ 89.16666667 146.33333333 260.66666667]
 [158.83333333 260.66666667 464.33333333]]


In [15]:
#1 (h)
import numpy as np
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
print("Inner product:",np.inner(x,y))
print("Outer product:",np.outer(x,y))


Inner product: [[17 52]
 [13 62]]
Outer product: [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]


In [16]:
#2 (a) 1
import numpy as np
array = np.array([[1, -2, 3],[-4, 5, -6]])
print("Absolute Value:",np.abs(array))

Absolute Value: [[1 2 3]
 [4 5 6]]


In [17]:
#2 (a) 2
import numpy as np
array = np.array([[1, -2, 3],[-4, 5, -6]])
print("array : ", array)
print("Mean of row : ",
       np.mean(array, 1))
print("median of row : ",
       np.median(array, 1))
print("standard deviation of row : ",
       np.std(array, 1))

print("Mean of column : ",
       np.mean(array, 0))
print("median of column : ",
       np.median(array, 0))
print("standard deviation of column : ",
       np.std(array, 0))

array :  [[ 1 -2  3]
 [-4  5 -6]]
Mean of row :  [ 0.66666667 -1.66666667]
median of row :  [ 1. -4.]
standard deviation of row :  [2.05480467 4.78423336]
Mean of column :  [-1.5  1.5 -1.5]
median of column :  [-1.5  1.5 -1.5]
standard deviation of column :  [2.5 3.5 4.5]


In [18]:
#2 (a) 3
import numpy as np
array = np.array([[1, -2, 3],[-4, 5, -6]])
print("array : ", array)
print("50th percentile of array : ",
       np.percentile(array, 50))
print("25th percentile of array : ",
       np.percentile(array, 25))
print("75th percentile of arraay : ",
       np.percentile(array, 75))

array :  [[ 1 -2  3]
 [-4  5 -6]]
50th percentile of array :  -0.5
25th percentile of array :  -3.5
75th percentile of arraay :  2.5


In [ ]:
#2 (b)
import numpy as np
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
r2 = np.floor(a)
r3 = np.ceil(a)
r4 = np.trunc(a)
r5 = [round(elem) for elem in a]
print("Floor:",r2)
print("Ceil:",r3)
print("Truncate:",r4)
print("Round:",r5)

Floor: [-2. -2. -1.  0.  1.  1.  3.]
Ceil: [-1. -1. -0.  1.  2.  2.  3.]
Truncate: [-1. -1. -0.  0.  1.  1.  3.]
Round: [-2, -2, 0, 0, 2, 2, 3]


In [ ]:
#3 (a)
import numpy as np
array = np.array([10, 52, 62, 16, 16, 54, 453])
# 1
print(np.sort(array))
# 2
indices = np.argsort(array)
print(indices)
# 3
arr1 = np.sort(array)
print("4 smallest elements of the array")
print(arr1[:4])
# 4
print("5 largest elements of the array")
print(arr1[-5:])

[ 10  16  16  52  54  62 453]
[0 3 4 1 5 2 6]
4 smallest elements of the array
[10 16 16 52]
5 largest elements of the array
[ 16  52  54  62 453]


In [19]:
#3 (b)
import numpy as np
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

floatele = array[array != array.astype(int)]
print ("Float elements:",floatele)
intele = array[array != array.astype(float)]
print ("Integer elements:",intele)

Float elements: [1.2 2.2]
Integer elements: []


In [28]:
#4

from PIL import Image
from numpy import asarray

image = Image.open('/content/ultimate-photo-editor-cloud-sync-mobile-thumb.webp')

data = asarray(image)
print(type(data))

print(data.shape)

image2 = Image.fromarray(data)
print(type(image2))

print(image2.mode)
print(image2.size)


with open("sample.txt", "w+") as f:
  data = f.read()
  f.write(str(data))

<class 'numpy.ndarray'>
(242, 304, 3)
<class 'PIL.Image.Image'>
RGB
(304, 242)
